name: todo_app
description: "A new Flutter project for task management."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# Restrição do SDK Dart
environment:
  sdk: "^3.5.0"  # Define a versão mínima do SDK Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8           # Ícones do iOS para Flutter
  firebase_core: ^3.6.0             # Firebase Core
  firebase_auth: ^5.3.1             # Autenticação com Firebase
  cloud_firestore: ^5.4.4           # Firestore para armazenamento remoto de dados
  firebase_storage: ^12.3.5         # Armazenamento de arquivos com Firebase
  path: ^1.8.3                      # Gerenciamento de caminhos, útil para SQLite
  sqflite: ^2.4.1                # SQLite para armazenamento local
  provider: ^6.1.2                 # Gerenciamento de estado com Provider
  intl: ^0.18.0                     # Para formatação de data e hora
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0             # Conjunto de lint para melhores práticas

flutter:
  uses-material-design: true        # Ativa o uso do Material Design
